import React from 'react';
import { X, Check, ShoppingBag, Sparkles } from 'lucide-react';
import { Product } from '../types';
import { formatINR } from '../utils/api';
import { useCart } from '../contexts/CartContext';

interface ComparisonModalProps {
  isOpen: boolean;
  onClose: () => void;
  products: Product[];
  comparisonData?: any;
}

export const ComparisonModal: React.FC<ComparisonModalProps> = ({
  isOpen,
  onClose,
  products,
  comparisonData
}) => {
  const { addToCart } = useCart();

  if (!isOpen || products.length === 0) return null;

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 sm:p-6 bg-black/80 backdrop-blur-md animate-in fade-in duration-200">
      <div className="bg-[#0f172a] border border-white/10 rounded-2xl w-full max-w-5xl max-h-[90vh] flex flex-col shadow-2xl overflow-hidden">
        
        {/* Header */}
        <div className="p-4 sm:p-6 border-b border-white/10 flex items-center justify-between bg-slate-900/60">
          <div className="flex items-center gap-2.5">
            <div className="w-8 h-8 rounded-lg bg-cyan-500/20 text-cyan-400 flex items-center justify-center border border-cyan-500/30">
              <Sparkles className="w-4 h-4" />
            </div>
            <div>
              <h2 className="text-lg font-bold text-white tracking-tight">
                AI Product Comparison Matrix
              </h2>
              <p className="text-xs text-slate-400">
                Side-by-side technical evaluation generated by the Shopping Agent
              </p>
            </div>
          </div>
          <button
            onClick={onClose}
            className="p-2 rounded-lg text-slate-400 hover:text-white hover:bg-white/10 transition"
          >
            <X className="w-5 h-5" />
          </button>
        </div>

        {/* Comparison Content */}
        <div className="p-4 sm:p-6 overflow-y-auto flex-1">
          <div className="grid grid-cols-1 md:grid-cols-3 gap-6 mb-8">
            {products.slice(0, 3).map((p) => (
              <div key={p.id} className="glass-panel p-4 rounded-xl border border-white/10 flex flex-col justify-between space-y-4">
                <div className="space-y-3">
                  <div className="aspect-video w-full rounded-lg overflow-hidden bg-slate-900">
                    <img
                      src={p.imageUrl}
                      alt={p.title}
                      className="w-full h-full object-cover"
                    />
                  </div>
                  <div>
                    <span className="text-[10px] uppercase font-bold text-indigo-400 tracking-wider">
                      {p.brand}
                    </span>
                    <h3 className="text-sm font-semibold text-white mt-0.5 line-clamp-2">
                      {p.title}
                    </h3>
                  </div>
                  <div className="text-base font-bold text-cyan-400">
                    {formatINR(p.price)}
                  </div>
                </div>

                <button
                  onClick={() => addToCart(p.id, 1, 'Added from Side-by-Side Comparison')}
                  className="w-full py-2 px-3 rounded-lg bg-indigo-600 hover:bg-indigo-500 text-white text-xs font-semibold flex items-center justify-center gap-1.5 transition cursor-pointer"
                >
                  <ShoppingBag className="w-3.5 h-3.5" />
                  <span>Add to Cart</span>
                </button>
              </div>
            ))}
          </div>

          {/* Specifications Table */}
          <div className="border border-white/10 rounded-xl overflow-hidden">
            <table className="w-full text-xs text-left border-collapse">
              <thead>
                <tr className="bg-slate-800/80 border-b border-white/10">
                  <th className="p-3 text-slate-300 font-semibold w-1/4">Specification</th>
                  {products.slice(0, 3).map((p) => (
                    <th key={p.id} className="p-3 text-indigo-300 font-semibold truncate max-w-[200px]">
                      {p.title.split(' ').slice(0, 3).join(' ')}
                    </th>
                  ))}
                </tr>
              </thead>
              <tbody className="divide-y divide-white/5">
                <tr className="hover:bg-white/5">
                  <td className="p-3 text-slate-400 font-medium">Price</td>
                  {products.slice(0, 3).map((p) => (
                    <td key={p.id} className="p-3 font-semibold text-white">
                      {formatINR(p.price)}
                    </td>
                  ))}
                </tr>
                <tr className="hover:bg-white/5">
                  <td className="p-3 text-slate-400 font-medium">Customer Rating</td>
                  {products.slice(0, 3).map((p) => (
                    <td key={p.id} className="p-3 text-amber-400 font-semibold">
                      ★ {p.rating.toFixed(1)} / 5.0 ({p.reviewCount} reviews)
                    </td>
                  ))}
                </tr>
                <tr className="hover:bg-white/5">
                  <td className="p-3 text-slate-400 font-medium">Stock Status</td>
                  {products.slice(0, 3).map((p) => (
                    <td key={p.id} className="p-3 text-emerald-400">
                      {p.inStock ? `Available (${p.stockCount} in stock)` : 'Out of Stock'}
                    </td>
                  ))}
                </tr>

                {/* Dynamic spec rows from comparisonData if available */}
                {comparisonData?.comparisonMatrix?.slice(0, 8).map((row: any, idx: number) => (
                  <tr key={idx} className="hover:bg-white/5">
                    <td className="p-3 text-slate-400 font-medium">{row.attribute}</td>
                    {row.values.map((v: any, valIdx: number) => (
                      <td key={valIdx} className="p-3 text-slate-200">
                        {v.value}
                      </td>
                    ))}
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </div>

        {/* Footer */}
        <div className="p-4 border-t border-white/10 bg-slate-900/60 flex items-center justify-end">
          <button
            onClick={onClose}
            className="px-4 py-2 rounded-lg bg-slate-800 hover:bg-slate-700 text-slate-300 text-xs font-semibold transition"
          >
            Close Comparison
          </button>
        </div>
      </div>
    </div>
  );
};
